# Generated by Django 4.2.2 on 2023-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.BigIntegerField(default=0)),
                ('libelle_article', models.CharField(max_length=255)),
                ('contenu_article', models.CharField(max_length=255)),
                ('date_artcle', models.DateTimeField(verbose_name='Date publication article')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.BigIntegerField(default=0)),
                ('nom_etudiant', models.CharField(max_length=255)),
                ('prenom_etudiant', models.CharField(max_length=255)),
                ('age_etudiant', models.CharField(max_length=255)),
                ('mail_etudiant', models.CharField(max_length=255)),
                ('tel_etudiant', models.CharField(max_length=255)),
                ('etudiant_password', models.CharField(max_length=255)),
            ],
        ),
    ]
