# Generated by Django 4.2.2 on 2023-09-30 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_etudiant', models.CharField(max_length=255)),
                ('nom_etudiant', models.CharField(max_length=255)),
                ('prenom_etudiant', models.CharField(max_length=255)),
                ('age_etudiant', models.CharField(max_length=255)),
                ('mail_etudiant', models.CharField(max_length=255)),
                ('tel_etudiant', models.CharField(max_length=255)),
                ('password_etudiant', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_filiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_matiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.IntegerField(default=0)),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant')),
                ('matieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.filiere'),
        ),
    ]
